name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Regression Test Backend
    runs-on: ubuntu-latest

    services:
      test-db-service:
        image: mysql:latest
        ports:
          - 3307:3307
        env:
          MYSQL_DATABASE: test_inventory_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_12345678
          MYSQL_ROOT_PASSWORD: test_rootroot 
          MYSQL_TCP_PORT=: 3307
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      keycloak-service:
        image: romabreu/keycloak-setup:latest
        ports:
          - 9090:9090
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
        options: >-
          --health-cmd "CMD-SHELL exec 3<>/dev/tcp/127.0.0.1/9090;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"
          --health-interval=10s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Build application
        working-directory: ./backend
        run: ./gradlew clean build -x test

      - name: Run Unit Tests
        working-directory: ./backend
        run: ./gradlew cucumberTest

      - name: Run Cucumber Tests
        working-directory: ./backend
        run: ./gradlew unitTest

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: JUnit Test Reports
          path: |
            build/reports/tests/unitTest/index.html
          retention-days: 30

      - name: Upload Cucumber test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Test Reports
          path: |
            build/reports/tests/cucumberTest/index.html
            target/cucumber-reports.html
          retention-days: 30
