name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Regression Test Backend
    runs-on: ubuntu-latest

    services:
      test-db-service:
        image: mysql:latest
        ports:
          - 3307:3307
        env:
          MYSQL_DATABASE: test_inventory_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_12345678
          MYSQL_ROOT_PASSWORD: test_rootroot
          MYSQL_TCP_PORT: 3307
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      keycloak-service:
        image: romabreu/keycloak-setup:latest
        ports:
          - 9090:9090
          - 9000:9000
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: true
        options: >-
          --health-cmd="[ -f /tmp/HealthCheck.java ] || echo 'public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }' > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
           node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
           package_json_file: 'frontend/quantum-stock/package.json'

      - name: Install Playwright for E2E tests and run tests
        working-directory: frontend/quantum-stock
        run: |
           pnpm install
           pnpm build
           pnpm start
           pnpm exec playwright install
           pnpm exec playwright test

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Build application
        working-directory: ./backend
        run: ./gradlew clean build -x test

      - name: Run Cucumber Tests
        working-directory: ./backend
        run: ./gradlew cucumberTest

      - name: Run Unit Tests
        working-directory: ./backend
        run: ./gradlew unitTest

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: JUnit Test Reports
          path: |
            /backend/build/reports/tests/unitTest/index.html
          retention-days: 30

      - name: Upload Cucumber test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Test Reports
          path: |
            backend/build/reports/tests/cucumberTest/index.html
            backend/target/cucumber-reports.html
          retention-days: 30

      - uses: actions/setup-node@v3
        with:
           node-version: '20'

      - uses: pnpm/action-setup@v2
        with:
           package_json_file: 'frontend/quantum-stock/package.json'

      - name: Install Playwright for E2E tests and run tests
        working-directory: frontend/quantum-stock
        run: |
           pnpm install
           pnpm exec playwright install
           pnpm exec playwright test
